### ISSUE TITLE
Qn: updating percent value programmatically?

### ISSUE THREAD

**Issue by eb1** [tomik23/circular-progress-bar#8]
Great work on this progress bar!

I've been incorporating it into a wizard for a mobile app (SPA), and the initial value looks great. Is there a way to update the percentage value and have the progress bar pick up on the change / update the SVG? Right now I have:

    // html
    <div class="pie" data-pie='{ "colorSlice": "#ffffff", "strokeWidth": 5, "size": 50, "fontColor": "#ffffff", "percent": 17 }'></div>

    // JS / initialize  
    this.progress = new CircularProgressBar('pie');
    ...

    ShowStep: function (number) {
        var totalSteps = 6;
        var progressPct = ((number * 1.0 / totalSteps) * 100).toFixed(1);
        // set the progress bar
        this.progress.percent = progressPct;
    }

...but setting the percent value doesn't appear to work.

**Comment by tomik23** [comment]
Hi, thanks for the comment.

In its current form, it is not possible to re-draw svg with new data.
The problem that arises is that some classes are dynamically generated from the IntersectionObserver. With one chart it would not be a problem, but as in the example where there are more than one charts, it is already a problem :)
Because to update, you would have to know what id has the svg progress bar, and depending on where you are on the page, it adds a different id. in addition, the length of the animation and a few other variables that prevent re-rendering of svg.

Of course, everything has to be done, but this involves a major revision of the script.

This is a great idea for future script development.

PS: And at the beginning it was supposed to be just a simple script to display one progress bar ;)

**Comment by eb1** [comment]
Hey, thanks for the comment. I suppose in the meantime I can hack my ShowStep() method a bit, and recreate the svg each time the progress bar moves:

    // html -- just add an id attribute to the div so we can directly reference it
    <div class="pie" id="progress" data-pie='{ "colorSlice": "#ffffff", "strokeWidth": 5, "size": 50, "fontColor": "#ffffff", "percent": 17 }'></div>

    // javascript (no initialization -- it's all created/updated within the progress bar update here)
    ShowStep: function (number) {
        var totalSteps = 6;
        var progressPct = ((number * 1.0 / totalSteps) * 100).toFixed(1);
        // set the progress bar
        $("#progress").html(""); // clear out the old svg
        var dp = JSON.parse($("#progress").attr("data-pie"));
        dp.percent = progressPct; // update progress value
        $("#progress").attr("data-pie", JSON.stringify(dp));
        $("#progress").attr("style", "");
        var progress = new CircularProgressBar('pie'); // create the progress bar
       ...

It _is_ kinda hacky, in that we're recreating the svg at each step and it has to update from 0% each time. But it does update the value. :-)

**Comment by tomik23** [comment]
Hi,
If you want to make it easier to change the percentages on the progress bar, a new version has appeared that makes it easier -  [update circular progress bar dynamically](https://github.com/tomik23/circular-progress-bar#update-circular-progress-bar-dynamically).
